language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

install:
  - "pip install requests"
  - "pip install coverage"
  - "pip install coveralls"
  - "pip install pandas"
  - "pip install seaborn"

script:
  - "coverage run --source=openaq setup.py test"

after_success:
  coveralls
